import React, { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useNavigate } from "react-router-dom";

import "./Dalle.scss";
import avtLogo from "../../assets/images/dalle-header.png";
import BackToTop from "../../components/backToTop/BackToTop";
import newRequest from "../../utils/newRequest";
import toastService from "../../utils/toastService.js";
import Photo from "../../components/photo/Photo";

const Dalle = () => {
  const currentUser = JSON.parse(localStorage.getItem("currentUser"));
  const navigate = useNavigate();
  const { data: allPosts, isLoading } = useQuery({
    queryKey: ["posts"],
    queryFn: async () => {
      const response = await newRequest.get(`/dalle`);
      return response.data.data.reverse();
    },
  });

  const handleClickGenerate = () => {
    if (!currentUser) {
      toastService.info("You must be logged in to continue!");
      navigate("/login");
      return;
    }
    navigate(`generate`);
  };

  return (
    <div className="dalle">
      <div className="header">
        <div className="headerLeft">
          <div className="title">The Community Showcase</div>
          <div className="subTitle">
            Browse through a collection of imaginative and visually stunning
            images generated by DALL-E AI
          </div>
          <button onClick={handleClickGenerate}>▶ Generate now</button>
        </div>
        <div className="headerRight">
          <img src={avtLogo} alt="" />
        </div>
      </div>

      <div className="container">
        <div className="mainContainer">
          <div className="renderPhoto">
            {isLoading ? (
              <div className="loading">Loading...</div>
            ) : (
              allPosts?.map((post, index) => {
                return <Photo key={post._id} {...post} idColor={index % 5} />;
              })
            )}
          </div>
        </div>
      </div>
      <BackToTop />
    </div>
  );
};

export default Dalle;
